### ISSUE TITLE
teaOS dwm patching

### ISSUE THREAD

**Issue by drmarwat** [SkywalkerSW5/teaOS#5]
is teaOS patched with this patch 
https://dwm.suckless.org/patches/autostart/
to create autostart file on teaos?
I want cbatticom and picom , dusnt and other programs to be started on the start of teaOS before the dwm starts

**Comment by SkywalkerSW5** [comment]
Hello,

The Autosrart patch is included with teaOS already.

To use it, you edit ~/.dwm/autostart.sh.

**Comment by drmarwat** [comment]
Thank you for your reply 
amazingly there is no ~/.dwm/ on my teaOS installation , I dont know why
Should I create it manually?

**Comment by SkywalkerSW5** [comment]
Yes, there has been some problems with the ISO not creating the directories. If its not there, then create the folder and the script.

**Comment by SkywalkerSW5** [comment]
Closed due to inactivity
